### ISSUE TITLE
Minor typo crates.io

### ISSUE THREAD

**Issue by eKristensen** [aisk/rust-ping#17]
Hi,

At https://crates.io/crates/ping the title says "Simle and naive ping implementation in rust."

I think you meant to say "_Simple_ and naive ping implementation in _Rust_."

I writing it here as I do not know where else to tell about it.

**Comment by aisk** [comment]
Thanks for pointing it out, and PRs are welcome!

**Comment by eKristensen** [comment]
> Thanks for pointing it out, and PRs are welcome!

I created a PR.
